This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./template.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file template.acn....done (145 entries accepted, 0 rejected).
Sorting entries....done (1111 comparisons).
Generating output file template.acr....done (162 lines written, 0 warnings).
Output written in template.acr.
Transcript written in template.alg.
