#!/bin/bash
set -e

sudo apt update
sudo apt install -y gnupg curl ca-certificates
curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
   --dearmor
echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
sudo apt update

sudo apt install -y mongodb-org
sudo systemctl start mongod
sudo systemctl enable mongod

sudo add-apt-repository ppa:open5gs/latest
sudo apt update
sudo apt install -y open5gs

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=20
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

sudo apt update
sudo apt install -y nodejs
curl -fsSL https://open5gs.org/open5gs/assets/webui/install | sudo -E bash -

MCC="001"
MNC="01"

FILES=("/etc/open5gs/amf.yaml" "/etc/open5gs/upf.yaml" "/etc/open5gs/nrf.yaml")

for FILE in "${FILES[@]}"; do
	if [ -f "$FILE" ]; then
		sudo sed -i "s/mcc: [0-9]*/mcc: $MCC/g" "$FILE"
		sudo sed -i "s/mnc: [0-9]*/mnc: $MNC/g" "$FILE"
	fi
done

sudo systemctl restart open5gs-*
